pairs:
  - BTC/USDT
  - ETH/USDT
  - SOL/USDT
  - AVAX/USDT
  - LINK/USDT
  - BNB/USDT
  - ICP/USDT
  - KAS/USDT
  - DOT/USDT
  - XRP/USDT
  - ADA/USDT
  - ALGO/USDT
  - HBAR/USDT
  - ZEC/USDT
  - AAVE/USDT
